
<?php

/////////////////////////////////////////////////////////////////////////
// --------------------------------------------------------------------//
// dailyAPHORISM   ----------------------------------------------------//
//---------------------------------------------------------------------// 
// by Alexander Junge (a.junge@aj-chs.de)                              //
// http://www.aj-chs.de                                                //
//                                                                     //
// Ich uebernehme keine Haftung fuer die Verwendung meines Scripts.    //
// dailyAPHORISM ist Freeware, daher kein Support!                     //
//                                                                    //\
// Die Hinweise zum Copyright muessen in diesem Script erhalten      // \\
// bleiben.                                                         //   \\  
//                                                                 //     \\
// (c) Copyright 2003 Alexander Junge                             //       \\
//                                                               ///////////\\
// Weitere Informationen auf meiner Homepage:                   //      //   \\
// http://www.aj-chs.de                                        //      //     \\
//                                                            //      //       \\
//////////////////////////////////////////////////////////////////////////////////
                                                                    //
                                                                   //  
                                                            //    //   
                                                             ////?>  


<?php
// Konfigurationsteil

//Interval fuer die Wiederholung festlegen
// 1 = Zitat wird per Zufall aus der Gesamtzahl gewaehlt, Austausch bei jedem Seitenaufruf (min. 2 Zitate benoetigt)
// 2 = Zitate werden taeglich ausgetauscht und woechentlich wiederholt ( 7 Zitate benoetigt) 
// 3 = Zitate werden taeglich ausgetauscht und monatlich wiederholt (31 Zitate benoetigt)
// 4 = Zitate werden monatlich ausgetauscht und jaehrlich wiederholt ( 12 Zitate benoetigt)
// 5 = Zitate werden taeglich ausgetauscht und jaehrlich wiederholt ( 365 !! benoetigt)
// 6 = Zitate werden stuendlich gewechselt und taeglich wiederholt ( 24 Zitate benoetigt)

$interval="1";

//Sprueche fuer jeden Aufruf

$daytalk=array(

"Ezra Pound"                   => "Je &auml;lter man wird, desto h&ouml;her sch&auml;tzt man die Kunst des konstruktiven Schweigens...",
"Mark Twain"                   => "Unkraut ist alles, was nach dem J&auml;ten wieder w&auml;chst...",
"Kurt Tucholsky"               => "Man mu&szlig; aus der Stille kommen, um etwas Gedeihliches zu schaffen...",
"Horaz"                        => "Wir loben die gute alte Zeit, leben aber gern in der Gegenwart...",
"Aristoteles"                  => "Gl&uuml;cklich, wer sich zuerst erzieht, ehe er sich anma&szlig;t andere zu bessern...",
"Alfred D&ouml;blin"           => "Wer &uuml;ber den Dingen steht, sieht weit, aber nicht genau...",
"Kurt Tucholsky"               => "Auch falsches Gl&uuml;ck erzeugt richtigen Neid...",
"Francois de La Rochefoucauld" => "Selten reicht unser Glaube weiter als unser Auge...",
"Tennessee Williams"           => "Die Wirklichkeit ist heute ein rei&szlig;ender Strom, in dem es von Nichtschwimmern wimmelt...",
"Maurice Blondel"              => "Eines der gr&ouml;&szlig;ten Hindernisse, die Zeit vern&uuml;nftig zu gebrauchen, ist der Wunsch, sie allzu gut auszun&uuml;tzen...",
"William Shakespeare"          => "Wo Worte selten sind, haben sie Gewicht...",
"Joachim Ringelnatz"           => "Die schmerzhaftesten Wunden sind Gewissensbisse...",
"Bert Brecht"                  => "Die Schw&auml;rmerei f&uuml;r die Natur kommt von der Unbewohnbarkeit der St&auml;dte...",
"Danny Kaye"                   => "Faulheit ist, wenn jemand mit dem Cocktail-Shaker in der Hand auf das n&auml;chste Erdbeben wartet...",
"Johann Wolfgang von Goethe"   => "Unsere W&uuml;nsche sind Vorboten desjenigen, was wir zu leisten imstande sind...",
"Cesare Pavese"                => "Man muss die Fehler, die man nicht ablegen kann, in Tugenden verwandeln...",
"Karl Valentin"                => "Heute ist die gute alte Zeit von morgen...",
"William Robertson Davies"     => "Die Erinnerung malt meist mit goldenem Pinsel...",
"Buddha"                       => "Wenn deine Einsicht meiner Lehre wiederspricht, so sollst du deiner Einsicht folgen...",
"W. Somerset Maugham"          => "Die meisten Menschen geben ihre Laster erst auf, wenn sie ihnen Beschwerden machen...",
"Henry Kissinger"              => "Erst wenn es um unbedeutenden Kleinkram geht, werden Auseinandersetzungen wirklich bitter...",
"Arthur Schopenhauer"          => "Architektur ist gefrorene Musik...",
"Fernandel"                    => "Es kann passieren, was will: Es gibt immer einen, der es kommen sah...",
"Jean Jacques Rousseau"        => "Nur dadurch, dass man das Gute tut, wird man gut...",
"Pablo Picasso"                => "Wenn etwas Absto&szlig;endes modern wird, ist es sofort anziehend...",
"Henrik Ibsen"                 => "Lebensk&uuml;nstler wissen, das es vor allem darauf ankommt, sich mit den richtigen Leuten zu vergleichen...",
"Gerhard Hauptmann"            => "Mit den Waffen der Seele k&ouml;nnen sich nur wenige verteidigen, ohne sich selbst zu verwunden...",
"Coco Chanel"                  => "Ein Freund ist jemand, der an deine T&uuml;r klopft, wenn dich alle Welt verlassen hat...",
"Wernher von Braun"            => "In Zukunft wird sich die Utopie beeilen m&uuml;ssen, wenn sie die Realit&auml;t einholen will...",
"Henry Ford"                   => "Zusammenkommen ist ein Beginn, Zusammenbleiben ein Fortschritt, Zusammenarbeiten ein Erfolg...",
"Glenn Close"                  => "Das Image ver&auml;ndert einen Menschen leichter als der Mensch sein Image...",
"Giovanni Guareschi"           => "Erfahrung ist, was bleibt, wenn man nichts mehr hat...",
"Emily Dickinson"              => "Manchmal mit dem Herzen, Selten mit der Seele, Kaum je mit Macht. Wenige - lieben &uuml;berhaupt.",
"Paramahansa Yogananda"        => "Werde ein Million&auml;r des L&auml;chelns",
"Rabindranath Tagore"          => "Gott achtet mich, wenn ich arbeite, aber er liebt mich, wenn ich singe.",
"Zen-Spruch"           	       => "Wenn man nur eine  Sache durch und durch verstanden hat, hat man alles verstanden.",
"Havelock Ellis"               => "Sex ist die Wurzel des Lebens, und wir werden nie lernen, Achtung vor den Leben zu haben, wenn wir nicht lernen, Achtung vor dem Sex zu haben.",
"Osho"           	       => "Sex wurde als die Erbs&uuml;nde bezeichnet, aber er ist weder 'erblich' noch ist er s&uuml;ndig.",
"Utara Tantra"                 => "Betrachte die Frau als eine G&ouml;ttin, deren spezielle Energie sie ist, und ehre ihre G&ouml;ttlichkeit.",
"Indisches  Sprichwort"        => "Liebe und das Selbst sind eines, und wer eines davon entdeckt, hat beides verwirklicht.",
"Ken Keyes"           	       => "Liebende Menschen sind gl&uuml;cklich, und gl&uuml;ckliche Menschen lieben.",
"Robert Bly"           	       => "Wie sich der Fluss an das Meer verschenkt, so zieht alles, was in mir ist, in dich...",
"Emily Dickinson"              => "Manchmal mit dem Herzen, Selten mit der Seele, Kaum je mit Macht. Wenige - lieben &uuml;berhaupt.",
"Friedrich Schiller"           => "Ach, wie gl&uuml;cklich sind die Toten.",
"Rumi"           	       => "Alles ausser Gott vergeht",
"Ramana Maharshi"              => "Warum willst du wissen, was du sein wirst, wenn du stirbst, wenn du noch nicht weisst, was du jetzt bist?",
"Afrikanische Weisheit"        => "Um ein Kind vern&uuml;nftig grosszuziehen, braucht man ein ganzes Dorf.",
"Thich Nath Hanh"              => "In jedem Augenblick hast Du eine Verabredung mit dem Leben. Jeden Augenblick, den Du vers&auml;umst, vers&auml;umst Du das Leben",
"Osho"           	       => "Etwas Besonderes sein, das will jeder; das ist etwas sehr Gew&ouml;hnliches. Etwas Gew&ouml;hnliches sein, das will fast keiner; das ist in der Tat etwas Besonderes.",
"Andreas Born"                 => "Jedes Leben ist des Lebens wert, jede Seele ihres Seins; jeder Mensch, geliebt zu werden.",
"Quelle leider ungekannt"      => "Es kommt nicht darauf an, wie alt man wird; es kommt darauf an, wie man alt wird.",
"Anthony de Mello"             => "Mit dem Leben ist es wie mit einem M&auml;rchen: nicht die L&auml;nge z&auml;hlt, sondern die Qualit&auml;t.",
"Josef Zeidler"                => "Was z&auml;hlt, ist nicht der Ordnungssinn, sondern das F&uuml;hlen; die Gewissheit des Herzens.",
"aus dem Buddhismus"           => "Werden kennt kein Ende, der Strom fliesst weiter. Jeder Augenblick ist neu, der Schmerz des Wachsens - der M&uuml;he wert!",
"Quelle leider ungekannt"      => "Mit den Idealen ist es wie mit den Sternen: man kann sie nicht erreichen, aber man kann sich an ihnen orientieren!",
"Mengtse"           	       => "Ein grosser Mensch ist der, der sein Kinderherz nicht verloren hat.",
"John Lennon"                  => "Leben ist das, was passiert, w&auml;hrend Du eifrig dabei bist, andere Pl&auml;ne zu machen.",
"Rainer Bacher"                => "Lieber blind auf beiden Augen, als blind im Herzen.",
"William Shakespeare"          => "Wenn man nicht weiss, wohin man will, kommt man am weitesten.",
"Quelle leider ungekannt"      => "Jede Stufe unseres Lebens hat ihre eigene Sch&ouml;nheit.",
"David Hume"           	       => "Das Leben des Menschen ist f&uuml;r das Universum nicht wichtiger als das einer Auster.",
"Quelle leider ungekannt"      => "Wirklich reich ist, wer mehr Tr&auml;ume in seiner Seele hat, als die Realit&auml;t zerst&ouml;ren kann.",
"Quelle leider ungekannt"      => "Wer keinen Mut zum Tr&auml;umen hat, hat keine Kraft zum K&auml;mpfen. ",
"Laurence J. Peter"            => "Fehler vermeidet man, indem man Erfahrung sammelt. Erfahrung sammelt man, indem man Fehler macht.",
"aus Persien"                  => "Die Seele geht zu Fuss.",
"aus China"                    => "Die Arbeit l&auml;uft Dir nicht davon, wenn Du Deinem Kind den Regenbogen zeigen willst. Aber der Regenbogen wartet nicht, bis Du mit der Arbeit fertig bist.",
"Antoine de St.-Exup&eacute;ry"       => "Wie wenig L&auml;rm machen die wirklichen Wunder.",
"Augustinus"                   => "In Dir muss brennen, was Du in anderen entz&uuml;nden m&ouml;chtest.",
"Diogenes"                     => "An seinen Feinden r&auml;cht man sich am besten dadurch, dass man besser wird als sie.",
"Kahlil Gibran"                => "Vertrauen ist eine Oase des Herzens, die von der Karawane des Denkens nie erreicht wird.",
"Selma Lagerl&ouml;f"               => "Kurz bevor die Sonne aufgeht, ist die Nacht am dunkelsten.",
"B. Maluche"                   => "Wenn Du einen Schritt machst.....Und ich einen Schritt mache k&ouml;nnten wir uns schon die H&auml;nde reichen.",
"Quelle leider ungekannt"      => "Manchmal muss ich die Augen schliessen, um klarer sehen zu k&ouml;nnen.",
"Quelle leider ungekannt"      => "Ein Freund ist ein Mensch, vor dem man laut denken kann.",
"Quelle leider ungekannt"      => "Zerbrich dir nicht den Kopf dar&uuml;ber, wie man Kinder erzieht, sie machen dir sowieso alles nach. Denke lieber dar&uuml;ber nach, welches Leben du f&uuml;r sie leben solltest.",
"Tibetanisches Sprichwort"     => "Begegnest du der Einsamkeit - hab&acute; keine Angst! Sie ist eine kostbare Hilfe mit sich selbst Freundschaft zu schliessen.",
"Quelle leider ungekannt"      => "Mit Problemen ist es wie mit den Bergen: Man kann sie nicht zur Seite schieben, man muss sie &uuml;berwinden.",
"Japanisches Sprichwort"       => "An dem Tag, an dem du zu reisen aufh&ouml;rst, wirst du angekommen sein.",
"Antoine de Saint-Exup&eacute;ry"     => "Der Mensch ist um so gr&ouml;sser, je mehr er er selbst ist.",
"Volksmund"                    => "&auml;rgere dich nicht dar&uuml;ber, dass der Rosenstrauch Dornen tr&auml;gt. Freue dich lieber dar&uuml;ber, dass der Dornenstrauch Rosen tr&auml;gt.",
"Quelle leider ungekannt"      => "Einem Sch&uuml;ler, der sich schrecklich f&uuml;rchtete, Fehler zu machen, sagte der Meister: 'Diejenigen, die keine Fehler machen, machen den gr&ouml;ssten aller Fehler: sie versuchen nichts Neues.'",
"Platon"                       => "Niemand von uns weiss, was der Tod ist; vielleicht ist er ja das h&ouml;chste Gut auf Erden?",
"Quelle leider ungekannt"      => "Mit der Liebe und der Entfernung ist es wie mit dem Feuer und dem Wind: Ist das Feuer zu schwach, bl&auml;sst es der Wind aus. Ist es aber gross, so wird es noch gr&ouml;sser.",
"Lao-tse"                      => "G&uuml;te in den Worten erzeugt Vertrauen; G&uuml;te im Denken erzeugt Tiefe; G&uuml;te beim Verschenken erzeugt Liebe.",
"Uhlenbruck"                   => "Manche Leute halten einen vollen Terminkalender f&uuml;r ein erf&uuml;lltes Leben.",
"Seneca"                       => "Es ist nicht wenig Zeit, die wir zur Verf&uuml;gung haben. Es ist viel Zeit, die wir nicht nutzen!",
"aus der Toscana"              => "Es nutzt nichts, auch wenn Du tausend Mal an der Olive zupfst - sie wird deshalb doch nicht fr&uuml;her reif.",
"Ernst Ferstl"                 => "Die modernste Form menschlicher Armut ist das Keine-Zeit-Haben.",
"Phil Bosmans"                 => "ZEIT ist keine Schnellstrasse zwischen Wiege und Grab, sondern Platz zum Parken in der SONNE.",
"John Steinbeck"               => "Die meiste Zeit verliert man damit, dass man Zeit gewinnen will.",
"Peter Ustinov"                => "Wer auf dem Weg zur Sonne ist, kommt durch ein paar hektische Luftspr&uuml;nge auch nicht schneller voran.",
"Quelle leider ungekannt"      => "Ein HUP ist die Zeitspanne zwischen dem Aufleuchten des gr&uuml;nen Lichts einer Ampel und dem Beginn des Hupkonzerts hinter dem ersten Wagen.",
"Selma Lagerl&ouml;f"               => "Man sollte nicht &auml;ngstlich fragen: 'Was wird und kann noch kommen?' Sondern sagen: 'Ich bin gespannt, was Gott jetzt noch mit mir vor hat!'",
"Alexander H&ouml;lle"              => "Der Zufall ist der gebr&auml;uchlichste Deckname von Gottes Plan.",
"Josef Zeidler"                => "Das, was der Mensch braucht, steckt in ihm. Gott ist in jedem, man muss Gott nicht erst zu den Menschen tragen.",
"Inschrift eines Dorfbrunnens" => "So sch&ouml;n und einfach ist mein Leben: Geben, immer nur geben.",
"Tibetisches Sprichwort"       => "Werde wieder wie ein staunendes Kind, das die Welt entdeckt - jeden Augenblick neu!",
"Quelle leider ungekannt"      => "Zahme V&ouml;gel tr&auml;umen von Freiheit. Wilde V&ouml;gel fliegen.",
"Marie von Ebner-Eschenbach"   => "Die gl&uuml;cklichen Sklaven sind die erbittertsten Feinde der Freiheit.",
"Rudolf Seiss"                 => "Freiheit ist die M&ouml;glichkeit, auf die M&ouml;glichkeit zu verzichten.",
"Bertolt Brecht"               => "F&uuml;r die, deren Zeit gekommen ist, ist es nie zu sp&auml;t.",
"Bertolt Brecht"               => "Wer k&auml;mpft, kann verlieren. Wer nicht k&auml;mpft, hat schon verloren.",
"Bertolt Brecht"               => "Kein Vormarsch ist so schwer, wie der zur&uuml;ck zur Vernunft.",
"Platon"                       => "Philosophie beginnt mit der F&auml;higkeit, sich zu wundern.",
"Erich K&auml;stner"                => "Entweder man lebt, oder man ist konsequent.",
"Weisheit aus China"           => "F&uuml;r Hungrige und Durstige ist leicht zu kochen.",
"Sebastian Brantus"            => "Die Welt will betrogen sein.",
"Marie von Ebner-Eschenbach"   => "Vieles erfahren haben heisst noch nicht Erfahrung besitzen.",
"Honor&eacute; de Balzac"             => "Liebende zweifeln an nichts oder an allem.",
"Robert Lembke"                => "Optimisten bauen Luftschl&ouml;sser, Pessimisten bauen Bunker.",
"Oedoen v. Hovarth"            => "Ich bin eigentlich ganz anders, aber ich komme so selten dazu.",
"Mark Twain"                   => "Immer wenn man die Meinung der Mehrheit teilt, ist es Zeit, sich zu besinnen.",
"David Herbert Lawrence"       => "Liebe ist kein Ziel; sie ist nur ein Reisen.",
"Hanns-Hermann Kesten"         => "Gott schuf die Welt aus dem Nichts. Der Mensch bef&ouml;rdert sie dorthin zur&uuml;ck.",
"Thomas Calyle"                => "Der schlimmste aller Fehler ist, sich keines solchen bewusst zu sein.",
"Victor Hugo"                  => "Melancholie ist das Vergn&uuml;gen, traurig zu sein.",
"Hugo Steinhaus"               => "Im Dunkeln denkt man tapferer, das Denken ist erotisch.",
"Anton Bruckner"               => "Wer hohe T&uuml;rme bauen will, muss lange beim Fundament verweilen.",
"Henry Ford"                   => "Unsere Fehlschl&auml;ge sind oft erfolgreicher als unsere Erfolge.",
"John Knittel"                 => "Alt ist man dann, wenn man an der Vergangenheit mehr Freude hat als an der Zukunft.",
"Charles Maurice Talleyrand"   => "Wenn die Unf&auml;higkeit einen Decknamen braucht, nennt sie sich Pech.",
"Christian Friedrich Hebbel"   => "Wer die Menschen kennenlernen will, der studiere ihre Entschuldigungsgr&uuml;nde.",
"Englisches Sprichwort"        => "Gl&uuml;ck ist, auch das zu lieben, was man tun muss und nicht nur das, was man tun will.",
"Walther Rathenau"             => "Die Erfindung des Problems ist wichtiger als die Erfindung der L&ouml;sung.",
"Karlheinz Deschner"           => "Wer in der Liebe Wunder erwartet, vergisst, dass er das gr&ouml;sste schon hat.",
"Th. Monnier"                  => "Ein Geschenk ist genau soviel wert, wie die Liebe, mit der es ausgesucht worden ist.",
"Kurt Tucholsky"               => "Das ist schwer: ein Leben zu zwein. Nur eines ist noch schwerer: einsam sein!",
"Marie von Ebner-Eschenbach"   => "Geistlose kann man nicht begeistern, aber fanatisieren kann man sie.",
"Schottisches Sprichwort"      => "Gl&uuml;ck ist, Freunde zu haben.",
"Henry M. Betrix"              => "Konzentriere dich auf das Wesentliche und mache es zu deinem Prinzip.",
"Lucius Annaeus Seneca"        => "Du wirst aufh&ouml;ren zu f&uuml;rchten, wenn du aufh&ouml;rst zu hoffen.",
"Wilhelm Busch"                => "Meistens hat, wenn zwei sich scheiden, einer etwas mehr zu leiden.",
"Sokrates"                     => "Wie viele Dinge es doch gibt, die ich nicht brauche!",
"Leonardo da Vinci"            => "Nichts Hohes erreicht ein K&uuml;nstler, der nicht an sich selber zweifelt.",
"Marie von Eber-Eschenbach"    => "Die Liebe hat nicht nur Rechte, sie hat auch immer recht.",
"Arthur Schopenhauer"          => "Vergeben und vergessen heisst, gemachte kostbare Erfahrungen zum Fenster hinauswerfen.",
"Volksmund"                    => "Der Tod geht zwei Schritte hinter dir. N&uuml;tze den Vorsprung und lebe.",
"Mongolisches Sprichwort"      => "Besser ein dummer Wanderer als ein Weiser, der zu Hause sitzt.",
"Afrikanisches Sprichwort"     => "Der Mensch ist die Medizin des Menschen.",
"Volksmund"                    => "Ob eine Sache gelingt, erf&auml;hrst du nicht, wenn du dar&uuml;ber nachdenkst, sondern wenn du es ausprobierst.",
"Winston Churchill"            => "Wenn zwei Menschen immer dasselbe denken, ist einer von ihnen &uuml;berfl&uuml;ssig.",
"Goethe"                       => "Niemand weiss, wie weit seine Kr&auml;fte gehen, bis er sie versucht hat.",
"Mark Twain"                   => "Wie wenig gen&uuml;gt, uns gl&uuml;cklich zu machen, wenn wir f&uuml;hlen, dass wir es verdient haben.",
"Victor Hugo"                  => "Verstehen heisst, mit dem Herzen hellsehen!",
"Liv Kortiva"                  => "Wer recht behalten will, bleibt allein. Erst recht, wenn er wirklich recht hat.",
"Ricarda Huch"                 => "Liebe ist das einzige, was nicht weniger wird, wenn wir es verschwenden.",
"Theodor Fontane"              => "Wenn man gl&uuml;cklich ist, soll man nicht noch gl&uuml;cklicher sein wollen.",
"Siegfried Lenz"               => "Alles Vergangene dauert, weil es nicht heilbar ist.",
"Balzac"                       => "Die Erinnerungen versch&ouml;nern das Leben, aber das Vergessen allein macht es ertr&auml;glich.",
"Giraudoux"                    => "Man erkennt den Irrtum daran, dass alle Welt ihn teilt.",
"Strellson Menswear"           => "M&auml;nner sind wie B&uuml;cher. Auf den Inhalt kommt es an, doch das &auml;ussere bestimmt oft den Erfolg.",
"Mchael Valliant"              => "L&auml;cheln ist die eleganteste Art einem Gegner die Z&auml;hne zu zeigen.",
"George Bernard Shaw"          => "Warum bekommt der Mensch die Jugend in einem Alter, in dem er nichts davon hat?",
"Yehudi Menuhin"               => "Der Mensch hat immer Vergn&uuml;gen und Erfolg mit Gl&uuml;ckseligkeit verwechselt.",
"Sir Winston Churchill"        => "Ein Diplomat ist ein Mann, der zweimal nachdenkt, bevor er nichts sagt.",
"Klaus Mann"                   => "Arbeit ist die ewige Last, ohne die alle &uuml;brigen Lasten unertr&auml;glich w&uuml;rden.",
"Sophokles"                    => "Das Schicksal nimmt nichts, was es nicht gegeben hat.",
"Johannes Brahms"              => "Orden sind mir wurscht, aber haben will ich sie.",
"Heinrich Nordhoff"            => "Man wird nicht dadurch besser, dass man andere schlecht macht.",
"Oscar Wilde"                  => "Man umgebe mich mit Luxus. Auf das Notwendige kann ich verzichten.",
"Andr&eacute; Maurois"                => "Das Schwierige am Diskutieren ist nicht, den eigenen Standpunkt zu verteidigen, sondern ihn zu kennen.",
"Marie von Ebner-Eschenbach"   => "&uuml;berlege wohl, bevor du dich der Einsamkeit gibst, ob du auch f&uuml;r dich selbst ein heilsamer Umgang bist.",
"Coco Chanel"                  => "Lebenskunst ist die Kunst des richtigen Weglassens.",
"J&uuml;disches Sprichwort"         => "Wenn du deine Tr&auml;ume erf&uuml;llt sehen willst, darfst du nicht schlafen.",
"Isaac Newton"                 => "Was wir wissen ist ein Tropfen, was wir nicht wissen, ein Ozean.",
"Paul Flora"                   => "Wenn Arbeit adelt, dann bleibe ich lieber b&uuml;rgerlich.",
"Jean Paul"                    => "Der Besitz macht uns nicht halb so gl&uuml;cklich, wie uns der Verlust ungl&uuml;cklich macht.",
"Friedrich Schiller"           => "Der Starke ist am m&auml;chtigsten allein.",
"Francis Bacon"                => "Zorn macht langweilige Menschen geistreich.",
"Heimito von Doderer"          => "Man muss manchmal von einem Menschen fortgehen, um ihn zu finden.",
"Christian Morgenstern"        => "Einander kennenlernen heisst lernen, wie fremd man einander ist.",
"Robert Musil"                 => "Keine Grenze verlockt mehr zum Schmuggeln als die Altersgrenze.",
"Oscar Wilde"                  => "Die Anzahl unserer Neider best&auml;tigt unsere F&auml;higkeiten.",
"H&ouml;lderlin"                    => "Was wir sind ist nichts, was wir suchen alles.",
"Ursula Andres"                => "Jede entt&auml;uschte Liebe macht ein bisschen immun gegen die n&auml;chste.",
"Albert Schweitzer"            => "Keine Zukunft vermag gutzumachen, was du in der Gegenwart vers&auml;umst.",
"Volksmund"                    => "Es sind immer nur die Schwachen, welche die Schwachen verachten!",
"G&uuml;nter Grass"                 => "Man muss nicht jede Erfahrung selber machen sollen.",
"Unbekannt"                    => "In der Wirklichkeit ist die Realit&auml;t ganz anders.",
"Marie Curie"                  => "Man braucht nichts im Leben zu f&uuml;rchten, man muss nur alles verstehen.",
"Danny Kaye"                   => "Es ist gef&auml;hrlich, &uuml;ber einen Witz zu lachen. Man bekommt ihn dann immer wieder zu h&ouml;ren.",
"Dale Carnegie"                => "Was du in anderen Menschen entz&uuml;nden willst, muss erst in dir selbst brennen.",
"Schopenhauer"                 => "Viele verlieren den Verstand deswegen nicht, weil sie keinen haben.",
"Georg Christoph Lichtenberg"  => "Vom Wahrsagen l&auml;sst sich wohl leben, aber nicht vom Wahrheit sagen.",
"Julian Huxley"                => "Wer ein Problem definiert, hat es schon halb gel&ouml;st.",
"&ouml;stliche Weisheit"            => "F&uuml;hlst du dich von jemand beleidigt, so stellst du dich geistig unter ihn.",
"Francois Mauriac"             => "Der Bau von Luftschl&ouml;ssern kostet nichts, aber ihre Zerst&ouml;rung ist sehr teuer.",
"G. Simmel"                    => "Gebildet ist, wer weiss, wo er findet, was er nicht weiss.",
"Goethe"                       => "Wo viel Licht ist, ist starker Schatten!",
"William Somerset Maugham"     => "Im Alter bereut man vor allem die S&uuml;nden, die man nicht begangen hat.",
"Marie von Ebner-Eschenbach"   => "Es gibt wenig aufrichtige Freunde - die Nachfrage ist auch gering.",
"Peter Bamm"                    => "Die Albernheit ist eine Erholung von der Umwelt.",
"Thomas Browne"                => "Niemand ist so uninteressant wie ein Mensch ohne Interesse.",
"Mark Twain"                   => "Man muss die Tatsachen kennen, bevor man sie verdrehen kann.",
"Ludwig B&ouml;rne"                 => "Tugenden und M&auml;dchen sind am sch&ouml;nsten, ehe sie wissen, dass sie sch&ouml;n sind.",
"Volksmund"                    => "Was dem Schmied bekommt, zerreisst den Schneider.",
"Volksmund"                    => "Ein Tropfen Liebe ist mehr, als ein Ozean an Wille und Verstand.",
"Abraham Lincoln"              => "Ich habe die Erfahrung gemacht, dass Leute ohne Laster auch sehr wenige Tugenden haben.",
"Nietzsche"                    => "Nicht durch Zorn, sondern durch Lachen t&ouml;tet man.",
"Unbekannt"                    => "Zum Weg der Erkenntnis f&uuml;hrt oft ein Pfad des Leichtsinns.",
"Robert Lembke"                => "Wer sp&auml;t zu Bett ging und fr&uuml;h heraus muss, weiss, woher das Wort Morgengrauen kommt.",
"Marcel Pagnol"                => "Wenn ein Mann &uuml;ber eine Frau nachzudenken beginnt, geh&ouml;rt er ihr schon halb.",
"Mark Twain"                   => "Der sicherste Weg, eine falsche Vorstellung hervorzurufen, ist es oft, die reine Wahrheit zu sagen.",
"Unbekannt"                    => "W&auml;hle einen Beruf den du liebst, und du brauchst niemals in deinem Leben zu arbeiten.",
"Robert Lembke"                => "Grunds&auml;tzliche Zustimmung ist die h&ouml;flichste Form der Ablehnung.",
"Papst Johannes XXIII"         => "Wo die Pferde versagen, schaffen es die Esel.",
"Hermann Hesse"                => "Leute mit Mut und Charakter sind den anderen Leuten immer sehr unheimlich.",
"Martin Buber"                 => "Am du werden wir erst zum ich.",
"Martin Kessel"                => "Einen Schuss W&uuml;ste braucht der Mensch - um des Gl&uuml;cks der Oase willen.",
"Unbekannt"                    => "In Frieden leben erfordert nicht grosse Worte, sondern viele kleine Schritte.",
"Buzulus"                      => "Ein kluger Mensch macht nicht alle Fehler selber, er gibt auch andern eine Chance.",
"Jean Guehenno"                => "Arm ist nicht der, der wenig hat, sondern der, der nicht genug bekommen kann.",
"Volksmund"                    => "Die k&uuml;rzeste Antwort auf eine Bitte ist die Tat.",
"Napoleon I. Bonaparte"        => "Man kann keinen Eierkuchen backen, ohne ein paar Eier zu zerschlagen.",
"David Ben Gurion"             => "Man ist besser dran mit einem intelligenten Feind als mit einem stupiden Freund.",
"Benjamin Franklin"            => "Alte Knaben haben genauso ihr Spielzeug wie die Jungen: der Unterschied liegt lediglich im Preis.",
"Nicolas Chamfort"             => "Es ist sehr schwer, das Gl&uuml;ck in uns zu finden, und es ist ganz unm&ouml;glich, es anderswo zu finden.",
"Jean Moliere"                 => "Die meisten Menschen sterben an ihren Medikamenten und nicht an ihren Krankheiten.",
"Sir Winston Churchill"        => "Nur Kinder, Narren und sehr alte Leute k&ouml;nnen es sich leisten, immer die Wahrheit zu sagen.",
"Billy Wilder"                 => "Ein Star ist jemand, der andere &uuml;berragt, weil er geschickt genug war, auf einen Stuhl zu steigen.",
"Mark Twain"                   => "Sammle erst die Fakten, dann kannst du sie verdrehen, wie es dir passt.",
"Oskar Wilde"                  => "Die Ehe ist gegenseitige Freiheitsberaubung in beiderseitigem Einvernehmen.",
"Goethe"                       => "Unsere W&uuml;nsche sind die Vorboten der F&auml;higkeiten, die in uns liegen.",
"Kyrilla Spiecker"             => "In einem Meer von Schmerz ertrinken die einen, die anderen lernen darin schwimmen.",
"Chinesische Weisheit"         => "Gegenseitige Hilfe macht selbst arme Leute reich.",
"Robert Walser"                => "Man lebt nicht, wenn man nicht f&uuml;r etwas lebt.",
"Francoise Sagan"              => "Wer ohne Grund traurig ist, hat Grund, traurig zu sein.",
"Erich Fromm"                  => "Bedingungslose Liebe ist eine unserer tiefsten Sehnsucht, nicht nur bei Kindern, sondern bei allen Menschen.",
"Brigitte Bardot"              => "Der ideale Ehemann ist ein unbest&auml;tigtes Ger&uuml;cht.",
"Sigmund Freud"                => "Wir streben mehr danach, Schmerz zu vermeiden als Freude zu gewinnen.",
"Jean de La Bruy&egrave;re"           => "Am sichersten macht man Karriere, wenn man anderen den Eindruck vermittelt, es sei f&uuml;r sie von Nutzen, einem zu helfen.",
"Moli&egrave;re"                      => "Wir sind nicht nur verantwortlich f&uuml;r das, was wir tun, sondern auch f&uuml;r das, was wir nicht tun.",
"Mahatma Gandhi"               => "Es gibt wichtigeres im Leben, als best&auml;ndig dessen Geschwindigkeit zu erh&ouml;hen.",
"Jean-Paul Sartre"             => "Vielleicht gibt es sch&ouml;nere Zeiten; aber diese ist die unsere.",
"Pearl S. Buck"                => "Kinder, die man nicht liebt, werden Erwachsene, die nicht lieben.",
"Goethe"                       => "Auch aus Steinen, die einem in den Weg gelegt werden, kann man sch&ouml;nes bauen.",
"Friedrich Hebbel"             => "Man hat nur dann ein Herz, wenn man es hat f&uuml;r andere.",
"Lec"                          => "Manchmal muss man verstummen, um geh&ouml;rt zu werden.",
"Unbekannt"                    => "Erfahrung ist eine n&uuml;tzliche Sache. Leider macht man sie immer erst kurz nachdem man sie brauchte.",
"Stefan Zweig"                 => "Ungeduld ist Angst.",
"Theodor Roosevelt"            => "Sprich leise und h&ouml;flich, aber trage stets einen dicken Kn&uuml;ppel bei dir.",
"Unbekannt"                    => "&uuml;bersieh nie die Menschen, denen du begegnest, denn sie pr&auml;gen dein Leben.",
"Erich K&auml;stner"                => "Wenn man genug Geld hat, stellt sich der gute Ruf ganz von selbst ein.",
"Albert Einstein"              => "Um ein tadelloses Mitglied einer Schafherde sein zu k&ouml;nnen, muss man vor allem ein Schaf sein.",
"Mahatma Gandhi"               => "Was man mit Gewalt gewinnt, kann man nur mit Gewalt behalten.",
"Karl Julius Weber"            => "Das Leben wird gegen Abend, wie die Tr&auml;ume gegen Morgen, immer klarer.",
"Henry Ford"                   => "Es gibt mehr Leute, die kapitulieren, als solche, die scheitern.",
"Unbekannt"                    => "Wer nicht hofft, dem wird das Unerhoffte nie begegnen.",
"Robert Lee-Frost"             => "Toleranz ist das unbehagliche Gef&uuml;hl, der andere k&ouml;nne am Ende vielleicht doch recht haben.",
"Alberto Moravia"              => "Dummheiten k&ouml;nnen reizend sein, Dummheit nicht.",
"Mark Twain"                   => "Menschen mit einer neuen Idee gelten so lange als Spinner, bis sich die Sache durchgesetzt hat.",
"Duke Ellington"               => "Probleme sind Gelegenheiten zu zeigen, was man kann.",
"R. Tagore"                    => "Wer zu gesch&auml;ftig Gutes tut, hat nicht die Zeit, gut zu sein.",
"Antoine de Saint-Exup&eacute;ry"     => "Leben heisst, langsam geboren werden. Es w&auml;re allzu bequem, fixfertige Seelen auszuleihen.",
"Peter Scholl-Latour"          => "Am sch&ouml;nsten ist jede Revolution vor ihrem Sieg - danach folgt die Ern&uuml;chterung.",
"Goethe"                       => "Es irrt der Mensch so lang er strebt.",
"Heinz R&uuml;hmann"           => "L&auml;cheln ist das Kleingeld des Gl&uuml;cks.",
"Hias Schaschko"               => "Leben gef&auml;hrdet deine Gesundheit.",
"Kurt Martin Magiera"          => "Wer hindert uns eigentlich daran, das zu tun, was wir von anderen erwarten?",
"Jean Paul"                    => "Der Furchtsame erschrickt vor der Gefahr, der Feige in ihr, der Mutige nach ihr.",
"Curt Goetz"                   => "Takt ist die F&auml;higkeit, einem anderen auf die Beine zu helfen, ohne ihm auf die Zehen zu treten.",
"Chinesisches Sprichwort"      => "F&uuml;rchte nicht, dass der K&ouml;rper, sondern, dass die Seele altert.",
"Franz Grillparzer"            => "Der Verstand und die F&auml;higkeit, ihn zu gebrauchen, sind zwei verschiedene Gaben.",
"Mark Twain"                   => "Das Recht auf Dummheit geh&ouml;rt zur Garantie der freien Entfaltung der Pers&ouml;nlichkeit.",
"Unbekannt"                    => "Ein Kind zu erziehen ist leicht. Schwer ist nur, das Ergebnis zu lieben.",
"Unbekannt"                    => "Am Ende bekommt man immer, was man will. Aber meistens zu sp&auml;t und eine Nummer zu klein.",
"George Bernard Shaw"          => "Es stimmt, dass Geld nicht gl&uuml;cklich macht. Allerdings meint man damit das Geld der anderen.",
"G. Ch. Lichtenberg"           => "Wir leben in einer Welt, worin ein Narr viele Narren, aber ein Weiser nur wenige Weise macht.",
"Gaston de L&eacute;vis"       => "Das Gl&uuml;ck ist ein Zustand der Ruhe, der weder Vergn&uuml;gen noch Schmerzen hervorbringt.",
"Francois Truffaut"            => "Man kann niemanden &uuml;berholen, wenn man in seine Fussstapfen tritt.",
"Jean-Jacques Rousseau"        => "Beleidigungen sind die Argumente derer, die Unrecht haben.",
"Kung-tse"                     => "Man muss sich einen Stecken in der Jugend schneiden, damit man im Alter daran gehen kann.",
"Blaise Pascal"                => "Jeder tr&auml;gt in sich das Urbild der Sch&ouml;nheit, deren Abbild er in der grossen Welt sucht.",
"Afrikanisches Sprichwort"     => "Nur wenn man sich im Weg irrt, lernt man den richtigen Weg kennen.",
"Jean-Paul Sartre"             => "Wer die Dummk&ouml;pfe gegen sich hat, verdient Vertrauen.",
"Matthias Claudius"            => "Sage nicht immer, was du weisst, aber wisse immer, was du sagst.",
"Unbekannt"                    => "Ein Weg entsteht dadurch, dass man ihn geht!",
"William James"                => "Die Kunst weise zu sein, ist die Kunst, zu wissen, was man &uuml;bersehen kann.",
"Unbekannt"                    => "Vor der Erleuchtung hackst du Holz und holst Wasser und nach der Erleuchtung hackst du Holz und holst Wasser.",
"Volksmund"                    => "Durch Eintracht macht man kleine Dinge gross, durch Zwietracht wird man grosse Dinge los.",
"Volksmund"                    => "Keine Windm&uuml;hle l&auml;uft dem Wind nach.",
"Lessing"                      => "Kein Mensch muss m&uuml;ssen.",
"Coco Chanel"                  => "Lebenskunst ist die Kunst des richtigen Weglassens.",
"Donald Robert Perry Marquis"  => "Wenn ein Mann erz&auml;hlt, er sei durch harte Arbeit reich geworden, dann frage ihn, durch wessen Arbeit.",
"Michael Douglas"              => "Frei ab 12 Jahren heisst, der Held kriegt das M&auml;dchen. Frei ab 16 heisst, der B&ouml;sewicht kriegt das M&auml;dchen. Frei ab 18 heisst, jeder Darsteller kriegt das M&auml;dchen.",
"Marcel Reich-Ranicki"         => "Die anst&auml;ndigen Menschen arbeiten um des Ruhmes und des Geldes willen. Die unanst&auml;ndigen wollen die Welt ver&auml;ndern und die Menschen erl&ouml;sen.",
"Howard Hughes"		       => "Ein reicher Mann ist ein armer Mann mit sehr viel Geld.",
"Heimito von Doderer"	       => "Man muss manchmal von einem Menschen fortgehen, um ihn zu finden.",
"Thomas Bernhard"	       => "Ich sehne mich nach dem Alleinsein, aber bin ich allein, bin ich der ungl&uuml;cklichste Mensch.",
"Heinrich B&ouml;ll"	       => "Wie alt man geworden ist, sieht man an den Gesichtern derer, die man jung gekannt hat.",
"Martin Buber"		       => "Alt sein ist eine herrliche Sache, wenn man nicht verlernt hat, was anfangen heisst.",
"Coco Chanel"		       => "Alter sch&uuml;tzt vor Liebe nicht, aber Liebe vor dem Altern.",
"Hand Kudszus"		       => "Alt werden heisst sich selbst ertragen lernen.",
"Burt Lancaster"	       => "Solange man neugierig ist, kann einem das Alter nichts anhaben.",
"William Somerset Maugham"     => "Jede Generation l&auml;chelt &uuml;ber die V&auml;ter, lacht &uuml;ber die Grossv&auml;ter und bewundert die Urgrossv&auml;ter.",
"Hans Moser"		       => "Die Menschen verlieren zuerst ihre Illusionen, dann ihre Z&auml;hne und ganz zuletzt ihre Laster.",
"Pablo Picasso"		       => "Die meisten Menschen brauchen sehr lang, um jung zu werden.",
"Peter Sirius"		       => "Wir werden alt, wenn die Erinnerung uns zu freuen beginnt. Wir sind alt, wenn sie uns schmerzt.",
"Horaz"			       	   => "Wer begonnen hat, der hat schon halb vollendet.",
"Hans Arndt"		       => "Nachdem er die Angst erfuhr, hatte er nur mehr Angst vor der Angst.",
"Jeremias Gotthelf"	       => "F&uuml;rchtet einer das Feuer, so riecht er allenthalben Rauch.",
"Arabisches Sprichwort"	       => "Es gibt kein Bergab, ohne dass vor ihm ein Bergan ist.",
"Bertolt Brecht"	       => "Die M&uuml;hen der Gebirge liegen hinter uns. Vor uns liegen die M&uuml;hen der Ebenen.",
"nach Hesidod"		       => "Ohne Fleiss kein Preis.",
"Laurence Sterne"	       => "Nirgends strapaziert sich der Mensch mehr als bei der Jagt nach Erholung.",
"G&uuml;nter Eich"	       => "Die eigentliche Antwort ist immer der Tod.",
"Jean Paul"		       => "Man h&ouml;rt in der Welt leichter ein Echo als eine Antwort.",
"Friedrich Nietzsche"	       => "Ein Beruf ist das R&uuml;ckgrat des Lebens.",
"Kurt Tucholsky"	       => "Eine der schauerlichsten Folgen der Arbeitslosigkeit ist wohl die, dass Arbeit als Gnade vergeben wird. Es ist wie im Kriege: Wer die Butter hat, wird frech.",
"Martin Buber"		       => "Jeder ist berufen, etwas in der Welt zur Vollendung zu bringen.",
"Goethe"		       => "Was aber ist deine Pflicht? Die Forderung des Tages.",
"Gotthold Ephraim Lessing"     => "Wer &uuml;berlegt, der sucht Bewegungsgr&uuml;nde, nicht zu d&uuml;rfen.",
"Seneca"		       => "Nichtwollen ist der Grund, Nichtk&ouml;nnen der Vorwand.",
"Ludwig B&ouml;rne"	       => "Die Fassung der Edelsteine erh&ouml;ht ihren Preis, nicht ihren Wert.",
"Franz Kafka"		       => "Die verbitterten Gesichtsz&uuml;ge eines Mannes sind oft nur die festgefrorene Verwirrung eines Knaben.",
"Christian Morgenstern"	       => "Sch&ouml;n ist eigentlich alles, was man mit Liebe betrachtet.",
"Albert Schweitzer"	       => "Mit zwanzig Jahren hat jeder das Gesicht, das Gott ihm gegeben hat, mit vierzig das Gesicht, das ihm das Leben gegeben hat, und mit sechzig das Gesicht, das er verdient.",
"Goethe"		       => "Nach Golde dr&auml;ngt, am Golde h&auml;ngt doch alles.",
"Goethe"		       => "Was Du ererbt von Deinen V&auml;tern hast, erwirb es, um es zu besitzen.",
"Schiller"		       => "Wer besitzt, der lerne zu verlieren.",
"Arthur Schopenhauer"	       => "Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.",
"Seneca"		       => "Aller Besitz ist vom Schicksal geborgt.",
"Benjamin Britten"	       => "Lernen ist wie Rudern gegen den Strom. Sobald man aufh&ouml;rt, treibt man zur&uuml;ck.",
"Chinesisches Sprichwort"      => "Wer fragt, ist ein Narr f&uuml;r f&uuml;nf Minuten. Wer nicht fragt, bleibt ein Narr f&uuml;r immer.",
"Goethe"		       => "Die beste Bildung findet ein gescheiter Mensch auf Reisen.",
"Dieter Hildebrandt"	       => "Bildung kommt von Bildschirm und nicht von Buch, sonst hiesse es ja Buchung.",
"Erich K&auml;stner"	       => "Der Mensch soll lernen. Nur die Ochsen b&uuml;ffeln.",
"John F. Kennedy"	       => "Es gibt nur eins, was auf Dauer teurer ist als Bildung: Keine Bildung.",
"Hans Margolius"	       => "Bildung ist nicht Wissen, sondern Interesse am Wissen.",
"Joseph Meyer"		       => "Bildung macht frei.",
"Oscar Wilde"		       => "Bildung ist etwas Wunderbares. Doch sollte man sich von Zeit zu Zeit daran erinnern, dass wirklich Wissenswertes nicht gelehrt werden kann.",
"Goethe"		       => "Doch der den Augenblick ergreift, das ist der rechte Mann.",
"Michael Gorbatschow"	       => "Wer zu sp&auml;t kommt, den bestraft das Leben.",
"Gottfried Keller"	       => "An einem offenen Paradiesg&auml;rtchen geht der Mensch gleichg&uuml;ltig vorbei und wird erst traurig, wenn es verschlossen ist.",
"Schiller"		       => "Was man der Minute ausgeschlagen, gibt keine Ewigkeit zur&uuml;ck.",
"Arthur Schnitzler"	       => "Bereit sein ist viel, warten k&ouml;nnen ist mehr, doch erst den rechten Augenblick n&uuml;tzen ist alles.",
"Friedl Beutelrock"	       => "Eine Kleinigkeit verr&auml;t oft mehr von dem Charakter eines Menschen als eine grosse Tat.",
"Alejandro Casona"	       => "B&auml;ume sterben aufrecht.",
"Laotse"		       => "Andere beherrschen erfordert Kraft. Sich selbst beherrschen fordert St&auml;rke.",
"Stanislaw Jerzy Lec"	       => "Charaktere sind unzerbrechlich - aber dehnbar.",
"Robert Lembke"		       => "Es gibt Leute, die als charaktervoll gelten, nur weil sie zu bequem sind, ihre Ansichten zu &auml;ndern.",
"Christian Morgenstern"	       => "Wer sich selbst treu bleiben will, kann nicht immer anderen treu bleiben.",
"Vincent van Gogh"          => "Mancher Mensch hat ein großes Feuer in seiner Seele, und niemand kommt, um sich daran zu wärmen.",
"Vincent van Gogh"          => "Was wäre das Leben, hätten wir nicht den Mut, etwas zu riskieren?",
"Karl Barth"                => "Freude ist die einfachste Form der Dankbarkeit",
"Winston Churchill"         => "Dem Kapitalismus wohnt ein Laster inne: Die ungleiche Verteilung der Güter. Dem Sozialismus hingegen wohnt eine Tugend inne: Die gleichmäßige Verteilung des Elends.",
"Winston Churchill"         => "Die Demokratie ist die schlechteste aller Staatsformen, ausgenommen alle anderen",
"Franz Kafka"               => "Verbringe die Zeit nicht mit der Suche nach Hindernissen – vielleicht ist keines da.",
"Gilbert Keith Chesterton"  => "Seit die Menschen nicht mehr an Gott glauben, glauben sie nicht an nichts, sie glauben allen möglichen Unsinn."
);

// Ende der Konfiguration //////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////////////////

$author=array_keys($daytalk);
$talk=array_values($daytalk);
$numbers=count($daytalk);
mt_srand((double)microtime()*1000000); 
$zufall=mt_rand(0,$numbers);

switch($interval){
case 1: $zitat="$zufall" ;break;
case 2: $zitat=date("w");break;
case 3: $zitat=date("j");break;
case 4: $zitat=date("n");break;
case 5: $zitat=date("z");break;
case 6: $zitat=date("H");break;
default:$zitat=$zufall;
};
?>
<strong><?php echo "$author[$zitat]";?>: </strong><?php echo  "$talk[$zitat]";?>
