
 <h2>Masochistischer Typus</h2>
      <h4>Ursächliche Faktoren</h4>
      <p>Störungen in der Zeit, wo das Kind anfängt, sein 'Nein' zu entwickeln (Reinlichkeitserziehung, frühes Trotzalter); Familie, in der Liebe und Anerkennung mit starkem Druck einhergehen. Beim Kind wird 'Nein' zerschlagen bzw. weggesteckt. Dominierende, sich aufopfernde Mutter erstickt das Kind ('Sei ein braves Kind', 'mach deiner Mutter Freude', 'iss brav deinen Teller leer',...), der Vater ist meist passiv und unterwürfig. Schuldgefühle bei Versuchen, selbständig zu sein, 'Nein' zu sagen. Im Vordergrund sind Kinder dann lieb und freundlich, im Hintergrund ist das 'Nein' immer da (Sabotage). Starke Fixierung auf Essen und Reinlichkeitserziehung. alle Wutanfälle werden im Keime erstickt (Hass und Groll aufgrund der Erniedrigungsgefühle).</p>
      <h4>Energetischer Zustand</h4>
      <p>Ladung im Inneren sehr stark, wird aber mit allen Mitteln zurückgehalten oder eingedämmt. Die äusseren Organe und Körperteile sind nur ungenügend geladen (Entladung und Entspannung unmöglich). Impulse nach oben und unten werden im Hals und in der Taille abgewürgt (Dabotage-Muskulatur) - ausgeprägte Angsttendenz.</p>
      <h4>Körperliche Erscheinung</h4>
      <img src="./seiten/koerpertypen/img/e_maso.gif" alt="der masochistische Typus" style="float: right; margin-left: 15px;">
      <p>Kurzer, dicklicher, muskulöser Körper, kurzer dicker Hals und Taille (zusammengestaucht). Vorgeschobenes Becken und eingezogenes Gesäss, Füsse nach aussen gerichtet; Knopfaugen; Fettring um die Taille, tiefsitzender ring muskulärer Spannung. Eingezogene Daumen, dunkel getönte Haut, meist starke Körperbehaarung.</p>
      <h4>Psychologische Begleitmerkmale</h4>
      <p>Angst: vernichtend bestraft zu werden, wenn er das 'Nein' zeigt und sich selbst behauptet; wenn er Gefühle zeigt. Äusserlich: Unterwürfigkeit ('Nur wenn ich mich selbst verleugne, bekomm ich deine Liebe'), Under-Dog ('Ich versuch es dir recht zu machen'); Schwäche, Leiden, Jammern, Sumpf, Gefallsucht. Darunter (unbewusst): Hass-, Negativismus-, Feindseligkeits- und Überlegenheitsgefühle ('Ich geb dir recht, und tu was du willst, aber ich behalte mich', 'Du kriegst mich nie'); jedoch Furcht, dass diese Gefühle in gewalttätiges Verhalten ausbrechen könnten. Aggressivität ist stark vermindert. Doch manchmal herausforderndes Verhalten, um den anderen dazu zu bringen, dass er heftig reagiert, um selbst auch explosiv reagieren zu können. Angst, aus sich heraus zu gehen oder nach etwas zu greifen (aus Furcht, verstümmelt zu werden, Kastrationsangst!), daher schwerfällige Energie, wenig Bewegung, Faulheit, Bequemlichkeit; traurige Ausstrahlung (wegen unterdrücktem Nein). Der masochistische Typ ist schwer fassbar, meist charmant, einwickelnd, ohne Angriffsfläche. (Nicht greifbar wie z.B. der psychopatische Typus). Konflikt zwischen Bedürfnis nach Liebe und Freiheitsbedürfnis ('Wenn ich frei bin, wirst du mich nicht lieben'). Der Masochist erklärt deshalb: 'Ich will dir gehorchen und du wirst mich dafür lieben'. Sexualität: Die Energie wird an der Taille abgewürgt; Angst, aktiv zu werden (wird gleichgesetzt mit Bestrafung); oft Kastrationsangst; Trägheit, Bequemlichkeit. Der masochistische Typus lässt andere für sich machen. Stärken: Freundlichkeit, Gemütlichkeit, Häuslichkeit, Hilfsbereitschaft; liebt das Harmonische; Möglichkeit, bei ihm zu entspannen; nichts Bedrohliches, Ruhe. Häufige Krankheiten: Verdauungsbeschwerden (v.a. Verstopfung), Asthma, Atembeschwerden, hoher Blutdruck.</p>
      <h4>Therapieziele</h4>
      <p>Im richtigen Augenblick mit Liebe aufzeigen, dass 'Nein' da ist. Manchmal ist auch Konfrontation notwendig (Stau erhöhen und damit 'Nein' spürbar machen, z. B. Luft anhalten oder zusammenpressen). Ekelgefühle sichtbar machen und annehmen. Der Maso ist oft sehr indirekt - Klarheit und Offenheit im Ausdruck fördern: lernen, zu sich selbst zu stehen, zu seinem 'Nein' zu stehen. Gut: Atmen, Körperarbeit, Bewegung, Tanzen, Tiefenmassage (PI, Rohlfing)...</p>
      <a href="javascript:history.back()">Zur&uuml;ck</a> 