
<h2>Oraler Typus</h2>
      <h4>Ursächliche Faktoren</h4>
      <p>Deprivation, Entzug im Babyalter; fehlende Befriedigung, weil die Mutter nicht da war, krank war oder zu wenig Zeit hatte; zu wenig Liebe, Wärme, Körperkontakt; zu frühes Abstillen; nicht genügende Ernährung über den Mund; In der Kindheit oft Enttäuschungs- und Frustrationserlebnisse bei versuchter Kontaktaufnahme oder suche nach Nähe und Wärme; oft depressive Phasen in später Kindheit oder früher Jugend; Kompensationsverhalten: frühreife Entwicklung, frühes Gehen und Sprechen.</p>
      <h4>Energetischer Zustand</h4>
      <p>Ungenügende Ladung, die zur Peripherie des Körpers zwar fliesst, aber zu schwach. Mangel an Energie in Augen, Händen, Füssen und Genitalien; am wenigsten in der unteren Körperhälfte; Geschlechtsorgane nicht voll erregungsfähig.</p>
      <h4>Körperliche Erscheinung</h4>
      <img src="./seiten/koerpertypen/img/e_oral.gif" alt="der orale Typus" style="float: right; margin-left: 15px;">
      <p>Längenwachstum betont; Körper lang und dünn; Muskulatur unterentwickelt, vor allem an Armen und Beinen; oft unterernährt; Körper wirkt, als fiele er in sich zusammen; Becken meist klein; Körperbehaarung spärlich, Augen ausdruckslos; schmollender, saugender Mund; durch Entzug der oralen Befriedigung ist Saugimpuls vermindert - kein richtiges tiefes Atmen möglich -  Energiepegel bleibt niedrig.</p>
      <h4>Psychologische Begleitmerkmale</h4>
      <p>Angst: Allein und verlassen zu sein; Angst, zu sterben, nicht existieren zu können, wenn nicht genug 'Nahrung' da ist; ständiges Gefühl von Mangel ('Es ist nicht genug für mich da'); Resignation; mangelnde Selbständigkeit ('hilf mir', 'ich brauch dich, um zu überleben', 'mach's für mich'); Verantwortung abgeben; Anklammern oder Anlehnen an andere; nicht gut oder überhaupt nicht allein sein können; übertriebenes Bedürfnis nach Kontakt mit anderen Menschen, nach deren Wärme und Hilfe. Unterdrückung starker Sehnsuchts- oder Wunschgefühle erzeugt inneres Gefühl der Leere, andere sollen diese Leere ausfüllen; starke Stimmungsschwankungen (stake Depression - grundlose Freude); Einstellung, 'man schulde ihm etwas'; oft saugende, vereinnahmende Art, Unfähigkeit, zu geben; verminderte Aggressivität; Kompensationsverhalten: übertriebene Selbständigkeit, die jedoch in Stress-Situationen zusammenbricht. Nähe kann nur auf der Basis des Bedürfnisses nach Wärme und Halt hergestellt werden (infantile Basis); Konflikt: 'Wenn ich unabhängig und selbständig bin, muss ich auf Halt und Wärme verzichten'. Oraler bleibt daher in abhängiger Position ('Ich kann mein Bedürfnis nach Halt und Wärme befriedigen, solange ich nicht selbständig bin'). Häufig geht der orale Typus gar keine Beziehung ein (was es ihm dann nicht möglich macht, sich mit seinen Ängsten zu konfrontieren). Wenn er eine eingeht, dann möchte er alles von diesem einen Partner haben. Essen: Orale essen meist sehr viel, nehmen aber nicht zu (wachsen nicht wirklich an dem was, sie bekommen). Sexualität: Hingabefähigkeit, aber kein Feuer; zärtlich, Schmelzbedürfnisse; Sinnlichkeit; manchmal lasch. Stärken: Schönheitsideal; Anhänglichkeit, Zartes; Feinfühligkeit für Situationen, Stimmungen, Atmosphäre; Ästhetik. Häufige Krankheiten: Depression, Kreislauf, Gelenke.</p>
      <h4>Therapieziele</h4>
      <p>Kontaktaufnahme mit der ohnmächtigen Wut, dem Terror, den man erlebt hat; Annehmen der Wut; oft ist aber Arschtritt notwendig, dass diese Wut überhaupt zugelassen wird; am Anfang oft Theater -  das ist aber schon ein grosser Sprung, um mit Energien überhaupt in Kontakt zu kommen; zuerst ist Resignation da, dann kommt Wut. Oraler Typ muss lernen, aus eigener Kraft zu geben und darauf zu vertrauen, dass er auch dann noch geliebt wird, wenn er unabhängig und selbständig ist; er muss lernen, die eigenen Bedürfnisse und Sehnsüchte direkt auszudrücken. Beschäftigung mit dem Positiven: Feiern, Tanzen, Energie in Bewegung setzen! Gut: Rebirthing, Dynamische Meditation.</p>
      <a href="javascript:history.back()">Zur&uuml;ck</a> 