
<h2>Psychopatischer Typus</h2>
      <h4>Ursächliche Faktoren</h4>
      <p>Anmerkung: Heute versteht man unter dieser Prägung einen Narzissten.</p>
      <p>Hauptfaktor ist ein sexuell verführender Elternteil (unterschwellig); Verführung mit dem Ziel, das Kind an sich zu binden (und dabei die eigenen narzisstischen Bedürfnisse zu befriedigen). Verführung wird vom Kind als Zurückweisung erlebt und damit auch als Mangel an Kontakt und Halt; Verführungsbeziehung lässt Dreiecksverhältnisse entstehen, in dem das Kind mit dem gleichgeschlechtlichen Elternteil konkurriert und sich daher nicht mit diesem identifizieren kann. In dieser Situation wird das Kind sehr verletzlich und es setzt sich über seine Bedürfnisse hinweg (tyrannisierender Typus) oder es manipuliert seine Eltern (manipulierender Typus). andere Faktoren sind starke Einschränkungen von aussen (verbale und nonverbale), die von den Eltern auf beherrschende oder manipulierende Art vermittelt werden: 'sei still!', 'gib Ruhe' (beherrschend) oder 'du brauchst nur lieb zu sein!', 'du bist ja so lieb, aber jetzt sei still!' (manipulativ). Das Kind will sich die Welt erobern und kämpft gegen diese Einschränkungen (indem es Geschwister, Spielkameraden tyrannisiert oder die Eltern manipuliert). Die Demütigungen durch die Eltern lässt Hass entstehen, und damit auch Schuldgefühle gegenüber ihnen.</p>
      <h4>Energetischer Zustand</h4>
      <p>Obere und untere Körperhälfte stehen energetisch in auffallendem Missverhältnis; alle Energie fliesst zum Kopf (ständiges Überlegen, wie eine Situation unter Kontrolle gebracht werden kann). Fluss von Energie und Gefühlen ist nach unten blockiert (starke Verkrampfungen in der Zwerchfell- und Taillengegend). Tyrannischer Typ: das Becken ist ungenügend geladen; alle Energie fliesst aufwärts; Becken starr. Manipulativer Typ: Becken zu stark geladen; nicht mit dem Kern verbunden.</p>
      <h4>Körperliche Erscheinung</h4>
      <img src="./seiten/koerpertypen/img/e_psycho.gif" alt="der psychopatische Typus" style="float: right; margin-left: 15px;">
      <p>Tyrannischer Typ: Oberkörper sehr stark entwickelt; unten schmal (oral); hochgezogene, 'gepolsterte' Schultern; herausgestreckte Brust; starrer Körperbau; Augen brillant; Kopf insgesamt sehr wach. Manipulativer Typ: Körper ausgeglichener; Rücken hyperflexibel; Augen verführend. Beide Typen haben Verspannungen in der Zwerchfellgegend, in der Augenpartie und am Hinterkopf.</p>
      <h4>Psychologische Begleitmerkmale</h4>
      <p>Angst: vor Erniedrigung und Niederlage; unterlegen zu sein; Angst vor Abhängigkeit; Angst vor Fehlern; Angst vor Bedürftigkeit. Das Grundgefühl der Minderwertigkeit äussert sich in dem Bedürfnis, andere zu steuern, zu manipulieren, die Kontrolle zu bewahren; gleichzeitig aber auch Abhängigkeit von denjenigen, die gesteuert und kontrolliert werden (d.h., der psychopatische Typ hat auch orale Persönlichkeit. Furcht, gesteuert zu werden (und damit benützt zu werden) bewirkt Bedürfnis, selbst zu steuern. Konflikt zwischen Unabhängigkeit bzw. Selbständigkeit und Bedürfnis nach Geborgenheit und Anschluss ('Ich kann dir nahe sein, wenn ich zulasse, dass du mich lenkst oder benutzt'); Zwickmühle (Bedürfnisse können nicht geleugnet werden, wie z.B. der schizoide Typus es tut, Risiko der Unabhängigkeit ist auch zu gefährlich - wie Oraler es macht); Der Psycho muss also Kontrolle über andere behalten, damit er Nähe zulassen kann; 'Du darfst mir nahe sein, solange du zu mir aufblickst' anstatt: 'Ich habe das Bedürfnis, dir Nahe zu sein'. Der psychopatische Typ muss in jeder Konkurrenzsituation Sieger bleiben ('Ich gebe niemals auf!' 'Ich lass mich nicht unterkriegen!' 'alles kann ich haben, wenn ich nur will'); wobei er fast immer mit Sexualität bzw. einschmeichelnden Verführungskünsten arbeitet. Er will alles unter Kontrolle haben (illusionäre Freiheit). Tyrannischer Typ: offensichtlich, konfrontierend, stolz (vor allem wenn starke rigide Anteile dabei sind); 'Ich bin der Stärkere!' Manipulativer Typ: trycki, hintenherum, schlau, verführerisch 'Du kriegst mich nicht' (umso stärker, je mehr Schizo- oder Masoanteile dabei sind). Leugnen von Gefühlen: Bedeutet, dass der psychopatische Typ sein Bedürfnis nach anderen Menschen leugnet; mit Manövern bringt er andere dazu, dass sie ihn brauchen, damit er seine Bedürfnisse nicht zeigen muss. Der psychopatische Typ kann nie entspannen, sich kaum hingeben; kontrolliertes Atemmuster! In der Gesellschaft ist er oft in leitenden Positionen; Machtmenschen, aber auch Herrschaft im positiven Sinn; auch Mode ist psychopatisch bestimmt. Sexualität: Lust und Sex ist Machtmittel, um Kontrolle auszuüben, andere zu benützen; die sexuelle Betätigung ist meist von Leistungszwang begleitet (häufig Impotenz als Begleiterscheinung); Lust spielt eine sekundäre Rolle; schwache energetische Impulse abwärts. Der psychopatische Typus 'tut' viel, kann sich kaum hingeben und geniessen. Stärken: Direktheit, Kraft und Stärke, mut, Wille, Angreifbarkeit (beim tyrannischen Typ); Begabung, andere aus der Reserve zu holen; Macht im positiven Sinn. Häufige Krankheiten: Magengeschwüre, Herzkrankheit (wenn er verliert) Midlife-Krise.</p>
      <h4>Therapieziele</h4>
      <p>Der psychopatische Typ muss dahin gebracht werden, dass er aufgibt und an die tieferen Schichten seiner Persönlichkeit kommt, d.h. an seine Bedürftigkeit, seine Traurigkeit, sein Verletztsein, seine Angst, manipuliert und kontrolliert zu werden. Möglichkeiten: durch Verunsicherung und Fehlschläge; durch Erfolgskarriere und darauf folgende Midliefe-Krise, durch Hingabe und Grounding; Verbindung zum Herz (Schmelzen!) er muss lernen zu nehmen, rezeptiv zu sein, seine Bedürfnisse zu äussern, zu bitten, dankbar zu sein. wichtig für Therapie: nicht auf Kampf einsteigen, Aufgaben stellen, aus dem Kopf herausbringen und Verbindung zum Herz herstellen. Zuerst kommt Wut, dann Traurigkeit. Gut: Körperarbeit, Pulsation, 'Kopfabnehmen', alle Energieübungen.</p>
      <a href="javascript:history.back()">Zur&uuml;ck</a> 
      
