
<h2>Rigider Typus</h2>
      <h4>Ursächliche Faktoren</h4>
      <p>Frustrations- und Versagenserlebnisse beim Streben nach erotischer Befriedigung im Alter, wo Gefühl für Sexualität auftaucht. Das Kind wird für sexuelle Interessen bestraft oder sexuelles Interesse eines Elternteiles wird vom Kind als bedrohlich erlebt. Zurückweisung des Bedürfnisses nach erotischer und sexueller Lust wird als Zurückweisung des Liebesbedürfnisses erlebt, als Verletzung des Stolzes. Das Kind holt sich Nähe dann indirekt, indem es zu manövrieren beginnt.</p>
      <h4>Energetischer Zustand</h4>
      <p>Viel Energie, die vom Zentrum nach aussen geht, aber an der Peripherie gestoppt wird; Gefühle fliessen, werden aber nur beschränkt ausgedrückt. Heisse Gliedmassen, starke Oberflächenspannung, Hauptspannung in äusserer Muskulatur (vor allem in den langen Muskeln - Streck- und Beugemuskeln). Der rigide Typus ist leicht erregbar, drückt aber seine eigenen Impulse nur wenig aus. Augen: energetisch aufgeladen, Ausdruck eines gebrochenen Herzens.</p>
      <h4>Körperliche Erscheinung</h4>
      <img src="./seiten/koerpertypen/img/e_rigide.gif" alt="der rigide Typus" style="float: right; margin-left: 15px;">
      <p>Der Körper ist gut proportioniert, muskulös, kompakt, sehr lebhaft und beweglich. Gute Hautfarbe, glänzende Augen; Beckenbereich zurückgeschoben (zurückgehaltene Sexualität), Hohlrücken, sehr betonten Po (Sexy-Po); betont gerade Rückgrat und hochgehaltenen Kopf (rigide - steife Haltung - Stolz!)</p>
      <h4>Psychologische Begleitmerkmale</h4>
      <p>Angst: verraten und ertappt zu werden, wenn er sich hingibt; Angst bei Hingabe und Unterwerfung die Freiheit zu verlieren, manipuliert und ausgenützt zu werden. Tendenz, sich steif zu halten (aus Stolz oder Unnahbarkeit) und nicht nachzugeben. Nachgeben wird mit Kollaps gleichgesetzt; starke Ich-Position ist gepaart mit starker Verhaltenskontrolle ('Ich kann frei sein, wenn ich mich nicht hingebe, wenn ich meine Energie nicht fliessen lasse', 'Ich gebe nichts her'); richtige Entladung ist daher kaum möglich. Restlose Hingabe und Öffnung wäre traumatisch, da dann die rigide Körperstruktur aufgeweicht wird und geballte Ladung von Energie zum Vorschein kommt - und damit auch die einstmals bestraften Bedürfnisse nach Lust und Sexualität. Rigide sind meist weltorientiert, ehrgeizig, kämpferisch und aggressiv; Passivität wird als Verwundbarkeit empfunden. Oft auch eigensinnig und störrisch (auf Stolz beruhend); Angst, lächerlich oder dumm zu wirken, wenn er sich hingibt oder sich gehen lässt. Rigide haben ein starkes Gefühl für sich selbst und können viel aus sich machen (vor allem wenn Struktur aufgeweicht ist); erfolgreiche Menschen, die sich gerne darstellen ('Darstellen ist alles'), die mit Sex-Appeal alles erreichen, wobei aber die Hingabe fehlt und das Herz nicht offen ist. Männer: Potenzprotze, phallisch disponierter, narzisstischer Typ. Frauen: viktorianischer Typ der hysterischen Frau, die Sex als Abwehr gegen Sexualität benützt; Frigidität. Nicht-Einlassen: Der rigide Typ bleibt letztendlich allein mit seiner Energie ('Ich zeig's dir, aber ich geb's dir nicht'). Konflikt: Freiheit gegen Kapitulation vor der Liebe ('Ich kann frei sein, wenn ich nicht den Kopf verliere und nicht vor der Liebe kapituliere'). Der Rigide achtet darauf, dass sein Verlangen und seine Liebe nicht zu stark werden. Sexualität: siehe Männer/Frauen; nicht Einlassen, keine Hingabe, Show, keine wirkliche Entladung und Entspannung, viel Energie. Stärken: Leidenschaftlichkeit, Energie, Ekstasefähigkeit, beneidenswertes Selbstgefühl, physische Kraft, schöner Körper, Beweglichkeit; wenn von Muster befreit: Hingabe. Häufige Krankheiten: Krebs, Koliken, Unfälle (nach innen gerichtete Aggression), Alkoholismus (mit starkem Alkohol) - Selbstzerstörung; alle aggressiven Krankheiten.</p>
      <h4>Therapieziele</h4>
      <p>Kontrolle aufgeben, Hingabe, Herz öffnen; Gut: alles, was Energie und Gefühle in Bewegung setzt (z. B. Pulsation). Rigide kommen aber selten in Therapie, da sie von sich überzeugt sind und für sie alles zum Besten steht; kaum Leidensdruck.</p>
      <a href="javascript:history.back()">Zur&uuml;ck</a> 
      