
<h2>Schizoider Typus</h2>
      <h4>Ursächliche Faktoren</h4>
      <p>Zurückweisung durch die Mutter schon während der Schwangerschaft, während der Geburt oder kurz danach; versteckte oder auch offene Feindseligkeit der Mutter; versuchte Abtreibungsversuche; Schocks; -- wird vom Kind als Bedrohung seiner Existenz empfunden; Mangel an jedem starken positiven Gefühl der Sicherheit oder Freude; in Kindheit häufig Tagträume, nächtliche Alpträume, Angstzustände; Rückzugsverhalten (manchmal Autismus); dominierende Gefühle von panischer Angst und blinder Wut.</p>
      <h4>Energetischer Zustand</h4>
      <p>Die innere Ladung ist im Kern (Zentrum) gestaut und eingefroren und wird von den äusseren Körperteilen und Organen, die den Kontakt zur Aussenwelt herstellen (Gesicht, Hände, Füsse, Genitalien) zurückgehalten. Energiefluss wird durch chronische Muskelspannungen an der Kopfbasis, an den Schultern, im Becken und an den Hüftgelenken verhindert. Schwache Impulsbildung; durch den Stau ist die innere Ladung jedoch explosiv (Gewalttätigkeit bei Durchbruch möglich). Energetische Spaltung der oberen und unteren Körperhälfte.</p>
      <h4>Körperliche Erscheinung</h4>
      <img src="./seiten/koerpertypen/img/e_schizo.gif" alt="der schizoide Typus" style="float: right; margin-left: 15px;">
      <p>Der Körper wirkt meist schmal, zusammengezogen, verkrampft. Spannungen in den Gelenken (Schädelbasis, Schultergelenke, Beingelenke, Beckengelenke, Zwerchfellgegend) und kleinen Muskeln (vor allem Muskeln um die Sprechwerkzeuge); extreme Inflexibilität oder Hyperflexibilität der Gelenke. Die Körperlinie ist häufig gebrochen (links/rechts-Verschiebungen), Diskrepanz zwischen den Körperhälften, Oben - Unten - Schnitt. Schiefe Kopf- und Körperhaltung (z. B. im Sitzen, beim Gehen und Stehen). Die Bewegungen sind oft mechanisch und unkoordiniert, Gliedmassen 'körperfremd', Füsse und Hände häufig kalt und verkrampft. Das Gesicht ist oft maskenhaft, die Augen leer und abwesend, die Haut ist wachsartig, durchsichtig.</p>
      <h4>Psychologische Begleitmerkmale</h4>
      <p>Angst: Identitätsverlust, Vernichtungsangst, Angst auseinanderzufallen, sich im Kontakt mit anderen zu verlieren. Begrenztes selbst-Gefühl, schwaches Ich, stark reduzierter Kontakt zum eigenen Körper und zu Gefühlen. Spaltung der Persönlichkeit in entgegengesetzte Einstellungen, dabei Schwierigkeiten, diese miteinander zu verbinden (z. B. Arroganz - Minderwertigkeit, Jungfrau - Hure). Durch schwache Ich-Abgrenzung Überempfindlichkeit und extreme Sensibilität - erfordert oft Abwehrmuster. Vermeiden von intimen, gefühlsbetonten Beziehungen bzw. Schwierigkeiten, diese herzustellen; «wenn ich mein Bedürfnis nach Nähe ausdrücke ist meine Existenz bedroht». Aktionen und Taten werden vom Kopf aus motiviert ('Mein Kopf ist mein Sein'), alles, was im Kopf ist, ist wirklich. Oft Flucht in Traumwelt, wenn die Realität nicht angenommen werden will, oft extrem wenig Kontakt zur Umgebung. Isolation ('Ich kann existieren, sofern ich keine Nähe brauche'). Kompensation der Angst durch aussergewöhnliche Leistungen - Künstler, Genies, - wobei der Motor für alles Tun die Suche nach der eigenen Identität ist. Oder: Suche nach extremen Erfahrungen, um sich spüren zu können (Bergsteigen, Autorennen, Drogen, etc.) Um das Gefühl des Getrenntseins von der Umwelt zu überwinden manchmal extreme Anpassung an die Umgebung (Chamäleon, Film von W. Allen: Zelig). Identität: schnelle Wechsel, heute habe ich gewonnen an Identität, morgen weiss ich nicht mehr, wer ich bin. Schlafen/Wachen: Schwierigkeiten, schlafen zu gehen und Aufzustehen (Wechsel von einem Zustand zum anderen wird als bedrohlich erlebt). Sexualität: wenig Ladung in Genitalien, aber Ekstasefähigkeit, kaum genitaler Orgasmus, oft sexuelle Fantasien (Mind_Fuck). Es geht nicht um Entladung, sondern um Aufladung, Auflösung, kosm. Orgasmus. Stärken des Typus (wenn Muster befreit sind): Vielseitigkeit, Verrücktheit, Aussergewöhnlichkeit, Phantasie, Tiefe, Sensibilität und Feinfühligkeit, Flexibilität, Anpassungsfähigkeit, Spielen versch. Rollen, Zugang zu anderen Wirklichkeiten. Häufige Krankheiten: Gelenkserkrankungen, Migräne, Alkoholismus/Drogen, Nieren/Blase, Sehstörungen, Kreislaufbeschwerden.</p>
      <h4>Therapieziele</h4>
      <p>Am wichtigsten: Gefühl für sich selbst entwickeln, Körperkontakt, Vertrauen! Raum geben, dass Klient wirklich in seine Extremteile hineingehen kann, es geht nicht darum, dass die versch. Identitäten zusammengebracht werden, sondern dass sie angenommen werden. Zum Kern (Angst der Vernichtung) kommen und die Angst annehmen, leben. Positive leere kann daraus entstehen. Gut: Alles was beschäftigt, am Boden hält, ins Hier und Jetzt bringt (Massage, Körperarbeit, Körperbewusstheit, Zentrierungsübungen, Bewegung, Tai Chi, aktive Meditation). Körperübungen erfordern oft viel Geduld, da die Angst da ist, auseinanderzufallen, kleine Schritte. Der schizoide Typus muss geschmolzen werden, direkte Konfrontation ist kaum möglich (geschicktes Ausweichen, 'Schlüpfrigkeit'), eher 'verführen' möglich. Wichtigste Voraussetzung für Therapie: zuerst hergestelltes Vertrauen und Sicherheit, Gefühl, wirklich angenommen zu sein.</p>
      <a href="javascript:history.back()">Zur&uuml;ck</a> 
      
