
<h1>Erkenne Dich selbst...</h1>
<p> <strong>...dann erkennst Du Gott.</strong> Seit Urzeiten war es verbreitetes Anliegen, mehr zu erfahren über sich und allenfalls etwas, dass ich als Gottähnliches Element bezeichnen möchte. Dabei denke ich an das Orakel von Delphi, aber auch an die Philosophen und Denker im alten Griechenland oder Rom. Spontan fällt mir kein Volk ein, dass nicht durch den Bau von Tempeln und anderen Kultstätten einer höheren Macht oder Gottheit huldigte. <img src="./seiten/Koerpertypen/img/delphi.png" alt="Tempel von Delphi" style="float:right; margin: 5px;"><br />
  Als Gott oder Gottheit wird meist ein übernatürliches Wesen bezeichnet, das über eine grosse und nicht naturwissenschaftlich beschreibbare transzendente Macht verfügt. Im Verständnis von Mythologien, Religionen und Glaubensüberzeugungen werden einem Gott oder mehreren Göttern besondere Verehrung zuteil und besondere Eigenschaften zugeschrieben, darunter oft die Eigenschaft, erster Ursprung, Schöpfer oder Gestalter der Wirklichkeit zu sein. Auch Vorstellungen einer nicht wesenhaften, unpersönlichen „göttlichen Kraft“ werden bisweilen – aus fehlendem Verständnis für fremde Religionen oder aus Vereinfachungsgründen – als Gott bezeichnet. <br />
  Verbunden mit der Frage, wer oder was Gott ist, ging immer die Frage einher, wer oder was wir sind. Eben: Erkenne Dich selbst, dann erkennst Du Gott. Einer der ältesten Klärungsversuche stammt noch aus der Zeit vor Christi von Hippocrates, der die sogenannte „Säftelehre“ mit seinen vier Grundtypen schuf. Der Typ wurde demnach durch ein Übermass eines bestimmten Körpersaftes vorgegeben.<br />
  Was in der Frühzeit vor allem zu spirituellen Antworten führte, wurde im Laufe der Zeit mit der Aufklärung logisch zu verstehen versucht. Ich denke an Descartes (Ich denke, also bin ich) und andere Philosophen. Und klar, spätestens seit Sigmund Freud und seiner Psychoanalyse ist scheinbar alles logisch erklärbar. </p>
<p> <img  src="./seiten/Koerpertypen/img/sofies_welt.jpg" width="150" alt="Sophies Welt von Jostein Gaarder" style="float:left; margin: 5px";/></a> Doch genug der langen Reden resp. der langatmigen Schreibereien. Wenn Du Dich für die Geschichte der Philosophie intressierst, dann empfehle ich gernde das Buch 'Sofies Welt', einem Roman über die Geschichte der Philosophie von Jostein Gaarder, in dem ich nach wie vor gerne blättere. <br />
  
<p>Falls Du aber gerne mehr über Dich herausfinden willst, dann empfehle ich Dir, die verschiedenen Tests hier auszuprobieren. Dabei kannst Du herausfinden, welcher Lerntyp Du bist <a href="https://arbeitsblaetter.stangl-taller.at/TEST/HALB/Test.shtml" alt="Testen, welcher Lerntyp Du bist" target="_blank">[LINK]</a>, oder Du erfährst hier, welcher Körpertyp Du bist <a href="?seiten/test.php">[LINK]</a>, oder...Du stöberst auf meiner Webseite und findest selber mehr über Dich heraus. Viele Erkenntnisse und viel Spass garantiert.</p>
<p style="float:left;">Last but not least: <img  src="./seiten/Koerpertypen/img/koerpertypen.jpg" width="150" alt="Ein wirklich lehrreiches Buch" style="float:right; margin: 5px";/></a><br />
  Ich habe wirklich viel über mich selbst gelernt durch Kurse und darüber hinaus mittels dem Buch 'Körpertypen - vom Typentrauma zum Traumtypen' von Roland Bäurle. Witzig und unterhaltsam beschreibt er die verschiedenen Prägungen der Menschen. Diese Lehre beruht auf der Erkenntnis, dass teilweise bereits während der Geburt, vor allem aber in den ersten Lebensjahren Prägungen entstehen, die uns ein Leben lang beeinflussen.<br />
  Durch einen Klick auf das Buch kannst Du mehr darüber erfahren, Rezensionen lesen und allenfalls direkt bestellen. </p>
